wallpaper {
  monitor = DP-3
  path = ~/Pictures/wallpapers/astolfo-hyppogryph.jpg
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = ~/Pictures/wallpapers/astolfo-city.jpg
  fit_mode = cover
}
