wallpaper {
  monitor = DP-3
  path = ~/Pictures/wallpapers/rimuru-wings-1.jpg
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = ~/Pictures/wallpapers/rimuru-cute-1.jpg
  fit_mode = cover
}
